name: Format, lint and test

on: [ push ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Compile and test"
        run: ./build-and-test.sh
      - name: "UI Test"
        run: ./ui-test.sh